overrides:
  '@walcu-engineering/pdfme-common': link:../../../../.local/share/pnpm/global/5/node_modules/@walcu-engineering/pdfme-common
  '@walcu-engineering/pdfme-converter': link:../../../../.local/share/pnpm/global/5/node_modules/@walcu-engineering/pdfme-converter
  '@walcu-engineering/pdfme-schemas': link:../../../../.local/share/pnpm/global/5/node_modules/@walcu-engineering/pdfme-schemas
